

module.exports = {
    functions: require("./others/functions"),
    logs: require("./others/logs"),
    vars: require("./others/vars"),
    effects: require("./music/effects"),
    music: require("./music/music-cammon"),
    //filters: require("./music/filters"),
    mstohours: require('./others/mstohours'),
    mysql: require("./mysql/mysql"),
    schema: require("./mysql/schema"),
    quote: require("./others/quote"),
    embed: require("./extenders/embed"),
    attach: require("./extenders/attach"),
    canvas: require("./canvas/canvas"),
    samp: require("./others/samp_carter"),
    splitText: require("./others/splitText"),
    imgDetect: require("./others/imgDetect"),
    translate: require("./others/translate"),
    ocr: require("./api/ocr"),
    googleTranslate: require("./api/googleTranslate"),
    defaltIcon: './img/png/uchiha.png',
    dbSend: require('./others/dbSend'),
    dbl: require('./others/dbl'),
    osu: require('./api/osu'),
    reloadcmds: require('./others/reloadcmds'),
    progess: require('./others/progess'),
    langs: require('./languages/index.js'), 
};